name: license_harvest_cli
description: A Command-Line Interface for report all licenses of dependencies
version: 0.0.2
homepage: https://github.com/lsaudon/license_harvest_cli
repository: https://github.com/lsaudon/license_harvest_cli
issue_tracker: https://github.com/lsaudon/license_harvest_cli/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.2
  cli_completion: ^0.4.0
  file: ^7.0.0
  mason_logger: ^0.2.10
  pana: ^0.21.35
  path: ^1.8.3

dev_dependencies:
  mocktail: ^1.0.1
  test: ^1.24.7

executables:
  license_harvest:
